parameters:
  - name: service_name
    type: object

  - name: app_path 
    displayName: Passenger App Group
    type: object

jobs:
- job: get_service_status
  displayName: Get Service Status
  pool:
    name: $(agentPool)
  steps:
    - checkout: IaC

    ###Eventually setup to use a template once it has been genericized### 
    # - template: ../../Steps/Utils/GetServiceStatus.yaml
    #   parameters: 
    #     service_name: ${{ parameters.service_name }}

    - script: |
        services=$(echo "${{ parameters.service_name }}" | tr ',' ' ')
        if echo "$services" | grep -qw "passenger"; then
          services="passenger"
        fi
        echo "##vso[task.setvariable variable=services]$services"
        echo "Service list: $services"
      displayName: Preprocess services

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          services=$(echo "$(services)")
          instances=$(echo "$(instance)" | tr ',' ' ')
          app_paths=$(echo "${{ parameters.app_path }}" | tr ',' ' ')

          for ip in $instances; do
            for service in $services; do
              if [ "$service" = "passenger" ]; then
                for app_group_path in $app_paths; do
                  echo Getting Status for $app_group_path
                  passenger_status=$(ssh -i $(key_path) ec2-user@$ip -o StrictHostKeyChecking=no "rvmsudo passenger-status | grep -A 10 /var/www/$app_group_path/current")
                  if [ $? -eq 0 ]; then
                    echo ==================================================================================
                    printf "%s\n" "$passenger_status"
                    echo ==================================================================================
                  else
                    echo Could Not Find Passenger App Group $app_group_path
                    overall_status=1
                  fi
                done
              fi 
            done
          done
      displayName: Passenger App Group Status
      condition: eq(variables['services'], 'passenger')

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          services=$(echo "${{ parameters.service_name }}" | tr ',' ' ')
          instances=$(echo "$(instance)" | tr ',' ' ')

          expanded_services=""
          for service in $services; do
            if [ "$service" = "sidekiq" ]; then
              expanded_services="$expanded_services sidekiq_assess_admin sidekiq_portal_user_mgmt sidekiq_rpt_info_svc"
            else
              expanded_services="$expanded_services $service"
            fi
          done      

          filtered_services=$(echo "$expanded_services" | tr ' ' '\n' | grep -vw "passenger" | tr '\n' ' ' | xargs)

          for ip in $instances; do
            ssh -i $(key_path) ec2-user@$ip -o StrictHostKeyChecking=no bash -c "' 
              overall_status=0
              for service in $filtered_services; do
                echo ==================================================================================
                echo Checking status of \$service on $ip...
                sudo systemctl status \$service
                if [ \$? -eq 0 ]; then
                  echo \$service is running on $ip
                  echo ==================================================================================
                else
                  echo \$service is not running or does not exist on $ip
                  overall_status=1
                fi
              done
            '"
          done
      displayName: Get Service Status